# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Minutes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Minutes

  pod 'AppCenter'
  pod 'AppCenter/Distribute'

  target 'MinutesTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'AppCenter'
  end

end
